name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: ./mvnw clean install
      env:
        # Set environment variables from GitHub Secrets
        APP_NAME: ${{ secrets.APP_NAME }}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
        DB_URL: ${{ secrets.DB_URL }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        HIKARI_POOL_SIZE: ${{ secrets.HIKARI_POOL_SIZE }}
        HIKARI_MIN_IDLE: ${{ secrets.HIKARI_MIN_IDLE }}
        HIKARI_IDLE_TIMEOUT: ${{ secrets.HIKARI_IDLE_TIMEOUT }}
        HIKARI_CONNECTION_TIMEOUT: ${{ secrets.HIKARI_CONNECTION_TIMEOUT }}
        HIKARI_MAX_LIFETIME: ${{ secrets.HIKARI_MAX_LIFETIME }}
        LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
